### ISSUE TITLE
Delivery location is a solid block

### ISSUE THREAD

**Issue by TheUntamed** [MattCzyr/EnderMail#1]
What happens if the delivery location is a solid block?

**Comment by MattCzyr** [comment]
If the delivery location isn't suitable (ex. it's inside a solid block, in a liquid, or floating), nearby Y coordinates will be scanned until a suitable one is found. If there are no suitable Y coordinates at the given X and Z position, the package will be marked as undeliverable and returned to the sender.

For more detail, check out [EntityEnderMailman::findValidDeliveryHeight](https://github.com/MattCzyr/EnderMail/blob/37adfd34db210e96a4e85a6c96bd5b9c8ec4c39b/src/main/java/com/chaosthedude/endermail/entity/EnderMailmanEntity.java#L219).
