### ISSUE TITLE
[1.15.2] Doesn't work with Quark

### ISSUE THREAD

**Issue by moulecake** [MattCzyr/EnderMail#12]
Hello, love your idea mod !
But, impossible to craft box because Quark create Oak_chest, Birch_chest, Spruce_chest etc...
Possible to do something :p ?
Thank you.

**Comment by MattCzyr** [comment]
I'll look into changing the recipe to use the ore dictionary chest instead of the vanilla chest.

**Comment by MattCzyr** [comment]
Fixed in 1.15.2-1.1.1
