### ISSUE TITLE
Ticking entity crash loop

### ISSUE THREAD

**Issue by Coolkc456** [MattCzyr/EnderMail#15]
Hello! I love this mod, but when sending items to my friend on my server, the mod sent the server into a crash loop after one of us sent each other the package. It sounded like we both sent our packages around the same time so I'm not sure who's enderman/package resulted in the crash. I was sending a block of cobalt from Tinker's Construct and he was sending a silver coin from Ordinary Coins. We were both sending our packages to a locker in the same dimension, the Overworld.
I've had this mod on my server for a week with people using it occasionally so it doesn't normally crash.

Here is a log: https://pastebin.com/nMbRckgd

I fixed the issue by removing the mod completely, starting up the server, stopping it, and reinstalling the mod to get rid of the enderman. I resent the package and everything was fine again.

**Comment by MattCzyr** [comment]
Fixed in version 1.1.3
