### ISSUE TITLE
Return package to sender upon sending to an invalid locker address

### ISSUE THREAD

**Issue by grundyboy34** [MattCzyr/EnderMail#25]
I've noticed that if you send a package to a locker ID in which no locker exists, the package simply gets sent to whatever was placed in the coordinates part of the address (or near world spawn if those were blank).
I find this very non-intuitive compared to how the average person would expect mail to work, and as typos can easily occur without catching them.

I'd suggest one of the two fixes:
1) When entering a Locker ID, change the GUI to disable the send button until a valid ID is entered.
2) When the enderman picks up the package, he simply brings the package back if he couldn't find a locker with the ID.

After looking into the code a bit, it seems option 2 may have the least required effort.

**Comment by MattCzyr** [comment]
Has been implemented in version 1.2.0.
