### ISSUE TITLE
Package sent from the nether to an invalid locker ID get delivered to -1, 128, -1

### ISSUE THREAD

**Issue by compilin** [MattCzyr/EnderMail#30]
I was testing out the mod (1.15.2-1.1.3) before installing it on my server and when I tried to deliver a package from the nether to the overworld, the package controller unexpectedly announced that it was "successfully delivered at -1, 128, -1". I went to check and there it was, on top of the bedrock roof. I tried multiple things, it seems to happen whether the locker is in the overworld or just non-existent. Packages only get marked as undeliverable in the nether if sent _from_ -1, 128, -1

**Comment by MattCzyr** [comment]
Has been fixed in version 1.2.0.
