### ISSUE TITLE
incompatibilities? 1.16 version sends packages to only one location, nowhere else

### ISSUE THREAD

**Issue by JetpackRescue** [MattCzyr/EnderMail#40]
I set up lockers, named them, i tried sending packages to specific coordinates, all of the packages end up stacked at -1, 80, -1.
each packages gets stacked on the prior package sent so the 80 increments upwards so the next package is sent to -1, 81, -1 and so on. Packages don't get put in lockers, even if they're sent to that specifically named locker, and packages don't get sent to any other coordinated other than the ones listed above.

When trying the mod on a Minecraft install without any other mods, it works. Are there any known incompatibilities?

**Comment by JetpackRescue** [comment]
Figured it out, your mod is incompatible with RoadRunner mod, which is a much needed performance enhancing mod.

https://www.curseforge.com/minecraft/mc-mods/roadrunner

would love if you could figure out the incompatibility and fix it, as I love this mod but I need roadrunner for performance.

**Comment by JetpackRescue** [comment]
Any chance this gets fixed soon?

**Comment by MattCzyr** [comment]
Will take a look later today.

**Comment by MattCzyr** [comment]
Try this beta version and let me know if the issue is fixed: https://www.dropbox.com/s/qw2lfd99twk9uhr/EnderMail-1.16.5-1.2.2-beta.jar?dl=0

**Comment by JetpackRescue** [comment]
It works! thanks for the fix!
