### ISSUE TITLE
Crash on Server start - 1.18.2-1.2.3

### ISSUE THREAD

**Issue by rckymtnrfc** [MattCzyr/EnderMail#44]
Attempted to load class com/chaosthedude/endermail/registry/EnderMailRenderers for invalid dist DEDICATED_SERVER

Forge 40.1.19
Endermail 1.18.2-1.2.3

server log file - https://pastebin.com/G3vAyQSs

**Comment by MattCzyr** [comment]
Fixed in version 1.2.4.
