### ISSUE TITLE
1.19 Crash upon start-up

### ISSUE THREAD

**Issue by Godz13** [MattCzyr/EnderMail#45]
Hi, my game crashes for some reason whenever i use the 1.19 version of this mod, it'd say that it hasn't loaded correctly and show java.lang.reflect.InvocationTargetException: null

Here's the crash report:
[crash-2022-08-05_23.32.46-fml.txt](https://github.com/MattCzyr/EnderMail/files/9269055/crash-2022-08-05_23.32.46-fml.txt)

Thanks,

**Comment by MattCzyr** [comment]
Should be fixed in version 1.19-1.2.6.
